### ISSUE TITLE
Remove "-PokemonChallenges" on quotes

### ISSUE THREAD

**Issue by EverOddish** [EverOddish/OpenFuji#25]
Also add a command to specify who a quote belongs to

**Comment by EverOddish** [comment]
Also add a command to specify who a quote belongs to

**Comment by wwselleck** [comment]
Had a similar suggestion in another stream. Maybe if a quote ends with `-{name}` (accounting for different whitespace), it can be attributed to {name}, and otherwise default to the streamer

**Comment by EverOddish** [comment]
Feature request for 2.0 re-write
